const FLAGS: Record<string, string> = {
  "France": "🇫🇷",
  "Germany": "🇩🇪",
  "Brazil": "🇧🇷",
  "Argentina": "🇦🇷",
  "Spain": "🇪🇸",
  "Portugal": "🇵🇹",
  "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "Italy": "🇮🇹",
  "Netherlands": "🇳🇱",
  "Belgium": "🇧🇪",
  "Croatia": "🇭🇷",
  "Uruguay": "🇺🇾",
  "Morocco": "🇲🇦",
  "Japan": "🇯🇵",
  "South Korea": "🇰🇷",
  "S. Korea": "🇰🇷",
  "Korea Republic": "🇰🇷",
  "Qatar": "🇶🇦",
  "Ecuador": "🇪🇨",
  "Senegal": "🇸🇳",
  "Iran": "🇮🇷",
  "USA": "🇺🇸",
  "United States": "🇺🇸",
  "Wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "Saudi Arabia": "🇸🇦",
  "Mexico": "🇲🇽",
  "Poland": "🇵🇱",
  "Australia": "🇦🇺",
  "Denmark": "🇩🇰",
  "Tunisia": "🇹🇳",
  "Costa Rica": "🇨🇷",
  "Canada": "🇨🇦",
  "Serbia": "🇷🇸",
  "Switzerland": "🇨🇭",
  "Cameroon": "🇨🇲",
  "Ghana": "🇬🇭",
  "Colombia": "🇨🇴",
  "Chile": "🇨🇱",
  "Peru": "🇵🇪",
  "Nigeria": "🇳🇬",
  "Egypt": "🇪🇬",
  "Algeria": "🇩🇿",
  "South Africa": "🇿🇦",
  "Sweden": "🇸🇪",
  "Norway": "🇳🇴",
  "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Ireland": "🇮🇪",
  "Greece": "🇬🇷",
  "Turkey": "🇹🇷",
  "Türkiye": "🇹🇷",
  "Austria": "🇦🇹",
  "Czech Republic": "🇨🇿",
  "Czechia": "🇨🇿",
  "Hungary": "🇭🇺",
  "Romania": "🇷🇴",
  "Slovakia": "🇸🇰",
  "Slovenia": "🇸🇮",
  "Ukraine": "🇺🇦",
  "Russia": "🇷🇺",
  "China": "🇨🇳",
  "New Zealand": "🇳🇿",
  "Panama": "🇵🇦",
  "Honduras": "🇭🇳",
  "Paraguay": "🇵🇾",
  "Venezuela": "🇻🇪",
  "Bolivia": "🇧🇴",
  "Jamaica": "🇯🇲",
  "UAE": "🇦🇪",
  "United Arab Emirates": "🇦🇪",
  "Iraq": "🇮🇶",
  "Syria": "🇸🇾",
  "Thailand": "🇹🇭",
  "Indonesia": "🇮🇩",
  "Malaysia": "🇲🇾",
  "North Macedonia": "🇲🇰",
  "Albania": "🇦🇱",
  "Finland": "🇫🇮",
  "Israel": "🇮🇱",
  "Ivory Coast": "🇨🇮",
  "Côte d'Ivoire": "🇨🇮",
  "Mali": "🇲🇱",
  "Guinea": "🇬🇳",
  "Zambia": "🇿🇲",
  "Congo": "🇨🇬",
  "DR Congo": "🇨🇩",
  "Cabo Verde": "🇨🇻",
  "Cape Verde": "🇨🇻",
  "Curaçao": "🇨🇼",
  "Bosnia and Herzegovina": "🇧🇦",
  "Haiti": "🇭🇹",
  "Uzbekistan": "🇺🇿",
  "Jordan": "🇯🇴",
  "Ethiopia": "🇪🇹",
  "Kenya": "🇰🇪",
  "Tanzania": "🇹🇿",
  "Uganda": "🇺🇬",
  "Zimbabwe": "🇿🇼",
};

export function getFlag(name: string): string {
  return FLAGS[name] ?? "🏳️";
}
